name: Build and deploy native image
on:
  push:
    branches:
      - spring-boot-3
env:
  REGISTRY_URL: crjuduboisnative.azurecr.io
  RESOURCE_GROUP: tmp-judubois-native
  FUNCTION_NAME: judubois-native

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Spring Boot Function with GraalVM
        run: |
          ./mvnw -Pnative native:compile
      - name: Build Azure Function native Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.FUNCTION_NAME }}/springboot-app-native:latest
          file: ./src/main/docker/Dockerfile.native
          context: .
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Function
        uses: Azure/functions-container-action@v1
        with:
          app-name: ${{ env.FUNCTION_NAME }}
          image: ${{ env.REGISTRY_URL }}/${{ env.FUNCTION_NAME }}/springboot-app-native:latest
