name: Build and deploy native image
on:
  push:
    branches:
      - spring-boot-3
env:
  # Replace with your registry URL
  REGISTRY_URL: crjuduboisnative.azurecr.io
  RESOURCE_GROUP: tmp-judubois-native
  PROJECT: judubois-native
  STORAGE_ACCOUNT: stjuduboisnative

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Spring Boot Function with GraalVM
        run: |
          ./mvnw -Pnative package
      - name: Build Azure Function native Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.PROJECT }}/springboot-app-native:${{ github.sha }}
          file: ./src/main/docker/Dockerfile.native
          context: .
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Docker image to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az functionapp update \
              --name ${{ env.PROJECT }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --storage-account ${{ env.STORAGE_ACCOUNT }} \
              --deployment-container-image-name ${{ env.REGISTRY_URL }}/${{ env.PROJECT }}/springboot-app-native:${{ github.sha }} \
              --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }} \
              --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
              --query "properties.configuration.ingress.fqdn" \
              --output tsv
